author: G1mi lo # 作者
description: G1mi lo's blog
keyword: hexo-theme, vuejs
favicon:

excerpt_link: Read more

menu:
 Heroes: /heroes
 Timeline: /archives/
 Projects: /project/
 Tags: /tags/
 About: /about/


# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# comment
# you can set gitment or uyan

comment: uyan

admin:
  username: g1mi
  password_hash: $2a$10$63VMvXh0wJUFOUZ.LSd77.aCB7X3NTfcUMq2Tfd57.vqkR.xajghC
  secret: g1miology


# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id:

about:
  banner: /css/images/about-banner.jpg
  avatar: https://avatars1.githubusercontent.com/u/12378287?s=460&v=4
  description: Just try to be A most considerate INFO'er.
  # Links
  weibo_username: 1
  twitter_username: 1
  github_username: g1mi
  zhihu_username: 1
  douban_username: 1