author: G1mi lo # 作者
description: G1mi lo's blog
keyword: hexo-theme, vuejs
favicon:

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Timeline: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# comment
# you can set gitment or uyan

comment: uyan


# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id:

about:
  banner: /css/images/about-banner.jpg
  avatar: https://avatars1.githubusercontent.com/u/12378287?s=460&v=4
  description: The end is always near.
  # Links
  weibo_username: yanm1ng
  twitter_username: yanm1ng
  github_username: yanm1ng
  zhihu_username: yummy1121
  douban_username: yanm1ng